# Generated by Django 5.2.11 on 2026-02-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50, unique=True)),
                ('subject_id', models.CharField(max_length=50)),
                ('sample_type', models.CharField(choices=[('Blood', 'Blood'), ('Plasma', 'Plasma'), ('CSF', 'CSF')], max_length=20)),
                ('collection_date', models.DateField()),
                ('status', models.CharField(choices=[('Collected', 'Collected'), ('Processing', 'Processing'), ('Stored', 'Stored'), ('Archived', 'Archived')], max_length=20)),
            ],
        ),
    ]
